CREATE TABLE IF NOT EXISTS `tbl_user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `password` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `salt` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `firstname` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `secondname` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `lastname` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `phone` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `login_ip` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `login_attempts` int(10) NOT NULL,
  `login_time` datetime NOT NULL,
  `validation_key` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password_strategy` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `requires_new_password` enum('0','1') COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vkontakte_id` int(10) unsigned DEFAULT NULL,
  `create_id` int(10) NOT NULL,
  `create_time` datetime NOT NULL,
  `update_id` int(10) NOT NULL,
  `update_time` datetime NOT NULL,
  `delete_id` int(10) NOT NULL,
  `delete_time` datetime NOT NULL,
  `create_ip` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` enum('0','1') COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `status` int(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `vkontakte_id` (`vkontakte_id`),
  KEY `password` (`password`),
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;